from onyx.llm.constants import LlmProviderNames

OPENAI_PROVIDER_NAME = "openai"

BEDROCK_PROVIDER_NAME = "bedrock"


OLLAMA_PROVIDER_NAME = "ollama_chat"
OLLAMA_API_KEY_CONFIG_KEY = "OLLAMA_API_KEY"

LM_STUDIO_PROVIDER_NAME = "lm_studio"
LM_STUDIO_API_KEY_CONFIG_KEY = "LM_STUDIO_API_KEY"

LITELLM_PROXY_PROVIDER_NAME = "litellm_proxy"

BIFROST_PROVIDER_NAME = "bifrost"

# Providers that use optional Bearer auth from custom_config
PROVIDERS_WITH_SPECIAL_API_KEY_HANDLING: dict[str, str] = {
    LlmProviderNames.OLLAMA_CHAT: OLLAMA_API_KEY_CONFIG_KEY,
    LlmProviderNames.LM_STUDIO: LM_STUDIO_API_KEY_CONFIG_KEY,
}

# OpenRouter
OPENROUTER_PROVIDER_NAME = "openrouter"

ANTHROPIC_PROVIDER_NAME = "anthropic"

AZURE_PROVIDER_NAME = "azure"


VERTEXAI_PROVIDER_NAME = "vertex_ai"
VERTEX_CREDENTIALS_FILE_KWARG = "vertex_credentials"
VERTEX_CREDENTIALS_FILE_KWARG_ENV_VAR_FORMAT = "CREDENTIALS_FILE"
VERTEX_LOCATION_KWARG = "vertex_location"

OPENAI_COMPATIBLE_PROVIDER_NAME = "openai_compatible"

ZAI_PROVIDER_NAME = "zai"
ZAI_DEFAULT_API_BASE = "https://api.z.ai/api/coding/paas/v4"

GOOGLE_AI_STUDIO_PROVIDER_NAME = "google_ai_studio"

OPENAI_CODEX_PROVIDER_NAME = "openai_codex"
OPENAI_CODEX_ACCESS_TOKEN_KEY = "codex_access_token"
OPENAI_CODEX_REFRESH_TOKEN_KEY = "codex_refresh_token"
OPENAI_CODEX_ID_TOKEN_KEY = "codex_id_token"
OPENAI_CODEX_TOKEN_EXPIRES_AT_KEY = "codex_token_expires_at"
OPENAI_CODEX_DISABLE_BUILTIN_TOOLS_KEY = "openai_codex_disable_builtin_tools"

CLAUDE_CODE_CLI_PROVIDER_NAME = "claude_code_cli"
CLAUDE_CODE_CLI_PATH_KEY = "cli_path"
CLAUDE_CODE_AUTH_MODE_KEY = "auth_mode"
CLAUDE_CODE_MCP_CONFIG_KEY = "mcp_config_json"
CLAUDE_CODE_OAUTH_TOKEN_KEY = "oauth_token"
CLAUDE_CODE_DISABLE_BUILTIN_TOOLS_KEY = "claude_code_disable_builtin_tools"

AWS_REGION_NAME_KWARG = "aws_region_name"
AWS_REGION_NAME_KWARG_ENV_VAR_FORMAT = "AWS_REGION_NAME"
AWS_BEARER_TOKEN_BEDROCK_KWARG_ENV_VAR_FORMAT = "AWS_BEARER_TOKEN_BEDROCK"
AWS_ACCESS_KEY_ID_KWARG = "aws_access_key_id"
AWS_ACCESS_KEY_ID_KWARG_ENV_VAR_FORMAT = "AWS_ACCESS_KEY_ID"
AWS_SECRET_ACCESS_KEY_KWARG = "aws_secret_access_key"
AWS_SECRET_ACCESS_KEY_KWARG_ENV_VAR_FORMAT = "AWS_SECRET_ACCESS_KEY"
